# Stage 1: Build the .NET app
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /source
COPY . .
WORKDIR /source/apps/ElectricityComparisonBackend
RUN dotnet restore
RUN dotnet publish -c Release -o /app

# Stage 2: Run the .NET app
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build /app .
ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000
ENTRYPOINT ["dotnet", "YourApp.dll"]
