services:
  frontend:
    build:
      context: .
      dockerfile: ../apps/ElectricityComparisonFrontend/Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ../apps/ElectricityComparisonBackend/Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
