services:
  backend:
    build:
      context: ..
      dockerfile: apps/ElectricityComparisonBackend/Dockerfile
    container_name: electricity-comparison-backend
    ports:
      - "5200:80"
    networks:
      - app-network

  frontend:
    build:
      context: ..
      dockerfile: apps/ElectricityComparisonFrontend/Dockerfile
    container_name: electricity-comparison-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge